# This is Python tutorial

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 5, 7], dtype='i')

In [ ]:
b = np.array([2, 3, 5])

In [ ]:
print(a)

In [ ]:
type(a)

In [ ]:
type(b)

In [ ]:
type(a)  # tells the type of "a"

In [ ]:
a.dtype

In [ ]:
a = np.array([[1,2,3], [4,5,6]])

In [ ]:
a.ndim # tells the dimention of "a"(array)

In [ ]:
a[0,2]

In [ ]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
b.ndim

In [ ]:
c = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[0,2,3], [4,5,6], [7,8,9]]])

In [ ]:
c.ndim

In [ ]:
c[1,0,0]

In [ ]:
c[1,0,1]

In [ ]:
type(c)

In [ ]:
c.shape # tells the shape of an array, output = (2, 3, 3), the first 2 means that there
        # are 2 two dimention arrays, and 3 means three one dimention and the last 
        # 3 means that each one dimention array has 3 elements

In [ ]:
A = np.arange(0,100) # makes an array which contains elements from 0 to 99
A = np.arange(0,100,2) # print an array which starts from 0 and jums two digists upto 100
A

In [ ]:
r = np.random.randint(1,100)
print(r)

In [ ]:
A = np.random.rand(1000)
print(A)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(A, bins = 100)

In [ ]:
B = np.random.randn(100000)
plt.hist(B, bins = 200)

In [ ]:
c = np.random.rand(2,3)
c.ndim

In [ ]:
A = np.arange(100)
B = A[3:10] #if do changes in B, the changes will also applies on A
print(B)

In [ ]:
B[0] = 169  #it will also change the elements in "A"

In [ ]:
B = A[3:10].copy()  # this will now copy the elements to B, and will not act as above

In [ ]:
A[::5]

In [ ]:
A[::-5]

In [ ]:
idx = np.argwhere(A== 169)[0][0] # returns the index of any number (eg 169)
idx

In [ ]:
A[idx] = 3
A

In [ ]:
A = np.round(10*np.random.rand(5,4)) # create 5x4 matrix, the elements in between 1 and 10 rounded
A

In [ ]:
A[1,:] # accessing the whole 2nd row of a matrix
A[:,1] # accessing the whole 2nd colomn of a matrix

In [ ]:
A.T # for doing transpose of a matrix
import numpy.linalg as la   # for linear algebra

In [ ]:
la.inv(np.random.rand(3,3))  # returns the inverse of a matrix

In [ ]:
A.sort(axis=0) # sort every column individually
A.sort(axis=1) # sort every row individually
A

In [ ]:
A = np.arange(100)
B = A[[3,5,6]]  # copy to B
B
B[0] = -4   # this will not do changes in A, because its a copy not a view

In [ ]:
B = A[A<40] # now B will contain all the elements that are less than 40
B = A[A%2==0] # now B will contain all the even elements
B = A[(A<40) & (A>30)]  # the symbol "&" is used for arrays
B

BROADCASTING

In [31]:
A = np.round(10*np.random.rand(2,3))
A

array([[7., 5., 2.],
       [2., 1., 1.]])

In [32]:
A+3

array([[10.,  8.,  5.],
       [ 5.,  4.,  4.]])

In [33]:
A+(np.arange(2).reshape(2,1))

array([[7., 5., 2.],
       [3., 2., 2.]])

In [34]:
B = np.round(10*np.random.rand(2,2))
B


array([[4., 2.],
       [6., 7.]])

In [ ]:
A

In [ ]:
C = np.hstack((A,B)) # it will concatenate A and B
C

In [ ]:
A = np.random.permutation(np.arange(10))
A

In [ ]:
A.sort() # or np.sort(A), it will also sort string array in alphabetic order
A

SPEED CHECKING

In [ ]:
B = np.random.rand(1000000)
%timeit sum(B)
%timeit np.sum(B) # or B.sum()  Universal sum function

In [ ]:
def mySum(G):
    s=0
    for x in G:
        s += x
    return s
print(mySum(B))

In [ ]:
%timeit mySum(B)

In [ ]:
A = np.round(10*np.random.rand(2,2))
A

In [ ]:
Determinant = A[0,0]*A[1,1] - A[0,1]*A[1,0]
Determinant

NUMPY PRACTICE QUESTIONS

In [ ]:
#Create a NumPy array of integers from 0 to 9.
A = np.arange(0,10)
A

In [ ]:
#Convert the data type of the array to float32.
A = A.astype(np.float32)
A.dtype

In [ ]:
# Create two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]).
# Perform element-wise addition, subtraction, multiplication, and division.
# Calculate the dot product of the two arrays.
A = np.array([1,2,3])
B = np.array([4,5,6])

Addition = A + B
Subtraction = A - B
Multiplication = A * B
Division = A / B

Dot_Product = 0
for i in range(3):
    Dot_Product += A[i] * B[i] 

print(Addition)
print(Subtraction)
print(Multiplication)
print(Division)
print(Dot_Product)


In [ ]:
# Create a 2D NumPy array of shape (4, 4) filled with random integers between 1 and 20.
# Extract the first two rows and the last two columns of the array.
# Replace all the elements in the third row with the number 5
A = np.round(20*np.random.rand(4,4))  # np.random.randint(1,21, size=(4,4))
print(A)

print(A[:2, 2:])

A[2] = 5
print(A)

In [ ]:
# Create a 3x3 matrix and extract the diagonal elements.
# Create a 3x4 matrix and extract all the elements from the second row.
A = np.round(10*np.random.rand(3,3))
print(A)
Diagnol_Elements = np.diag(A)
print("Diagnol Elements =",Diagnol_Elements)

B = np.round(10*np.random.rand(3,4))
print(B)
print("Secont row elements =",B[1])

In [ ]:
# Create a 3x3 identity matrix.
# Create a 3x3 matrix of random integers and find its transpose.
# Calculate the inverse of the matrix.
import numpy.linalg as la

Identity_Matrix = np.eye(3) 
print(Identity_Matrix)

A = np.random.randint(1,10,size = (3,3))
print(A)
print(A.T)

inverse = la.inv(A)
print(inverse)


In [ ]:
# Create a 1D array of 12 elements and reshape it into a 3x4 matrix.
# Flatten the 3x4 matrix back into a 1D array.
# Stack two 2D arrays vertically and horizontally.
Arr = np.arange(0,12)
print(Arr)
reshaped = Arr.reshape(3,4)
print("Reshaped to 3x4 Matrix\n",reshaped)

Flatten = reshaped.reshape(1,12)  # or we can use "reshaped.flatten()"
print("Flattened",Flatten)

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

vstacked = np.vstack((A,B))
print("Vertical Stack\n",vstacked)

hstacked = np.hstack((A,B))
print("Horizontal Stack\n",hstacked)

In [43]:
# Create a NumPy array with random integers between 1 and 100.
# Use boolean indexing to extract all elements greater than 50.
# Replace all elements greater than 80 with 0.

Arr = np.random.randint(0,100,size = (1,100))

print(Arr[Arr>50])

Arr[Arr>80]=0
print(Arr)

[59 61 61 64 91 78 88 53 88 83 53 67 60 90 95 85 93 99 74 73 84 86 61 84
 80 87 60 79 70 57 97 88 66 60 79 60 54 96 92 74 98 58 62 80 79 53 72 73
 61 64 89 65]
[[59 61 47 61 50  3 21 25 30 64 26  0 78  0 46 53  0  0 53 67 29 60 50 33
   0  0  0 33  0  0 74 73  0 39  0 27 35 61  0 80  0 49 60 41  5 30 35 46
  16 36 79 11 70 23 57 42 39  0  6  0  8  1 33 66 60  6 79 42 15 60 54 18
   0 42  0  6 74  0 58 62 41  2 80 79 25 53 72  5 73 61 64 37 42 39  8  0
  14 25 65  2]]


In [ ]:
# Create a 4x3 matrix and a 1x3 array.
# Add the 1x3 array to each row of the 4x3 matrix using broadcasting.
Matrix = np.random.randint(0,10,size=(4,3))
Array = np.random.randint(0,10, size=(1,3))

Sum = Matrix + Array

print("Matrix\n", Matrix)
print("Array\n", Array)
print("Summation\n", Sum)

Matrix
 [[2 4 3]
 [0 4 3]
 [6 1 0]
 [8 1 7]]
Array
 [[4 9 8]]
Summation
 [[ 6 13 11]
 [ 4 13 11]
 [10 10  8]
 [12 10 15]]
